ProjectManager.MVC/Controllers/AssumptionsController.cs
namespace ProjectManager.MVC.Controllers
{
    using System;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    /// <summary>
    ///     Handles requests for the assumptions page.
    /// </summary>
    public sealed class AssumptionsController : Controller
    {
        /// <summary>
        ///     The logger.
        /// </summary>
        private readonly ILogger<AssumptionsController> _logger;

        /// <summary>
        ///     Creates a new instance of the <see cref="AssumptionsController"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AssumptionsController(ILogger<AssumptionsController> logger)
        {
            this._logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        ///     Displays the assumptions page.
        /// </summary>
        /// <returns>An <see cref="IActionResult"/> representing the assumptions page.</returns>
        [HttpGet]
        public IActionResult Assumptions()
        {
            this._logger.LogInformation("Entered GET method Assumptions().");

            return this.View();
        }
    }
}

ProjectManager.MVC/Controllers/DecisionsController.cs
namespace ProjectManager.MVC.Controllers
{
    using System;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    /// <summary>
    ///     Handles requests for the projects page.
    /// </summary>
    public sealed class DecisionsController : Controller
    {
        /// <summary>
        ///     The logger.
        /// </summary>
        private readonly ILogger<DecisionsController> _logger;

        /// <summary>
        ///     Creates a new instance of the <see cref="DecisionsController"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DecisionsController(ILogger<DecisionsController> logger)
        {
            this._logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        ///     Redirects to the decisions page.
        /// </summary>
        /// <returns>An <see cref="IActionResult"/> representing the decisions page.</returns>
        [HttpGet]
        public IActionResult Decisions()
        {
            this._logger.LogInformation("Entered GET method Decisions().");

            return this.View();
        }
    }
}

ProjectManager.MVC/Controllers/RisksController.cs
namespace ProjectManager.MVC.Controllers
{
    using System;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    /// <summary>
    ///     Handles requests for the risks page.
    /// </summary>
    public sealed class RisksController : Controller
    {
        /// <summary>
        ///     The logger.
        /// </summary>
        private readonly ILogger<RisksController> _logger;

        /// <summary>
        ///     Creates a new instance of the <see cref="RisksController"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public RisksController(ILogger<RisksController> logger)
        {
            this._logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        ///     Redirects to the risks page.
        /// </summary>
        /// <returns>An <see cref="IActionResult"/> representing the risks page.</returns>
        [HttpGet]
        public IActionResult Risks()
        {
            this._logger.LogInformation("Entered GET method Risks().");

            return this.View();
        }
    }
}

ProjectManager.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Projects" asp-action="Projects">ProjectManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Projects">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actions" asp-action="Actions">Actions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Decisions" asp-action="Decisions">Decisions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Risks" asp-action="Risks">Risks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assumptions" asp-action="Assumptions">Assumptions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProjectManager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>